# Generated by Django 5.2.17 on 2026-08-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hospitalauditlog_patient_medicalhistory_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=50, unique=True)),
                ('file_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(default='DICOM', max_length=20)),
                ('study_instance_uid', models.CharField(blank=True, default='', max_length=255)),
                ('series_instance_uid', models.CharField(blank=True, default='', max_length=255)),
                ('sop_instance_uid', models.CharField(blank=True, default='', max_length=255)),
                ('modality', models.CharField(default='Chest X-Ray', max_length=50)),
                ('body_part', models.CharField(default='Chest', max_length=50)),
                ('status', models.CharField(choices=[('INGESTING', 'Ingesting'), ('READY_FOR_AI', 'Ready for AI'), ('AI_PROCESSING', 'AI Processing'), ('AI_COMPLETED', 'AI Completed'), ('AI_FAILED', 'AI Failed'), ('QUARANTINED', 'Quarantined')], default='READY_FOR_AI', max_length=30)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_studies', to='api.patient')),
                ('xray_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_studies', to='api.xrayrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
